---
title: "People"
---


```{r, message=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
people <- read_csv(here::here("people_db.csv"))
```


## Project leadership

```{r}
print_table <- function(x) {
  x %>%
    mutate(Name = paste0("[", name, "](mailto:", email, ")")) %>%
    select(Name, Role, Institution) %>%
    arrange(desc(Role), Institution, Name) %>%
    knitr::kable("html") %>%
    kableExtra::kable_styling("striped") %>%
    kableExtra::column_spec(1, width = "30%") %>%
    kableExtra::column_spec(2, width = "35%") %>%
    kableExtra::column_spec(3, width = "35%")
}

print_table2 <- function(x) {
  x %>%
    mutate(Name = paste0("[", name, "](mailto:", email, ")")) %>%
    select(Name, discipline, org) %>%
    arrange(discipline, Name, org) %>%
    knitr::kable("html") %>%
    kableExtra::kable_styling("striped") %>%
    kableExtra::column_spec(1, width = "30%") %>%
    kableExtra::column_spec(2, width = "35%") %>%
    kableExtra::column_spec(3, width = "35%")
}

print_table3 <- function(x) {
  x %>%
    mutate(Name = paste0("[", name, "](mailto:", email, ")")) %>%
    select(Name, Institution, Responsibilities) %>%
    arrange(Name, Institution, Responsibilities) %>%
    knitr::kable("html") %>%
    kableExtra::kable_styling("striped") %>%
    kableExtra::column_spec(1, width = "30%") %>%
    kableExtra::column_spec(2, width = "35%")%>%
    kableExtra::column_spec(3, width = "35%") 
}
people %>%
  filter(grepl("PI", Role)) %>%
  print_table()
```


## Collaborators

```{r}
people %>%
  filter(grepl("Collaborator", Role)) %>%
  print_table3()
```

## Affiliated Faculty
```{r}
# people %>%
#   filter(grepl("Affiliated", role)) %>%
#   print_table2()
```


