---
title: "CUE Ethics:  Evaluating Frameworks for Incorporating Computing Across the Curriculum"
---

## Project abstract

This award will test pathways for the delivery of computing across the curriculum in the context of undergraduate degrees at residential liberal arts colleges. The project will be organized as a Networked Improvement Community (NIC) that includes faculty from three colleges representing 10 distinct disciplines, as well as the heads of computer science and data science or data analytics at all three institutions. The multi-institutional NIC will provide an important opportunity for the project team to determine the most effective methods for delivering computer science (CS) content and working with non-CS faculty across a range of institutional governance and departmental structural differences. This project addresses the national desire to prepare larger and more diverse student populations for careers in both CS and non-CS fields, including careers in scientific and non-scientific disciplines.

Project activities are five-fold. First, the project will identify a set of core computing concepts that should be learned by every student today, particularly those students who are applying computing in non-CS fields. Second, it will rigorously evaluate the relative effectiveness of venues, including curriculum and course structure, for exposing students to the core computing concepts. Third, the project will analyze the kind and extent of preparation, guidance, and support necessary for non-CS faculty to incorporate and teach computing concepts in their courses. Fourth, it will analyze the extent to which the addition of computing concept material impacts student acquisition of disciplinary knowledge in non-CS courses. Lastly, it will analyze the impact on affiliated non-CS faculty with regard to their own teaching and research as they learn more about computing, and work collaboratively with other non-CS faculty on integration of computing into courses. By including fields that are more demographically diverse than CS, the researchers expect to broaden the pool of students who learn about computing and its applications. By integrating ethical considerations into the teaching of core computing concepts from the start, it is expected that students will learn to naturally ask ethical questions as part of their computational problem solving instead of as an afterthought. Finally, the project will develop a guiding document for similar institutions on how to effectively infuse core computing concepts across an institution in a "computing across the curriculum" approach. This IUSE: CUE project is co-funded by the EHR/DUE and all CISE Directorates CNS, CCF, IIS, and OAC, reflecting the project's alignment with the broader goals of the IUSE: EHR program in DUE and complementary programs in CISE.




### About CUE Ethics 

[NSF's IUSE:CUE](https://www.nsf.gov/pubs/2019/nsf19546/nsf19546.htm) program focuses on the preparation of a diverse student population careers in both CS and non-CS fields. The goal of this NSF solicitation is to support teams of Institutions of Higher Education (IHEs) in re-envisioning the role of computing in interdisciplinary collaboration within their institutions. In addition, NSF will encourage partnering IHEs to use this opportunity to integrate the study of ethics into their curricula, both within core CS courses and across the relevant interdisciplinary application areas.building capacity for harnessing the data revolution at the local, state, national, and international levels to help unleash the power of data in the service of science and society. Projects in this program are being jointly funded by the NSF's Harnessing the Data Revolution Big Idea; the Directorate for Computer and Information Science and Engineering, Division of Information and Intelligent Systems; the Directorate for Education and Human Resources, Division of Undergraduate Education; the Directorate for Mathematical and Physical Sciences, Division of Mathematical Sciences; and the Directorate for Social, Behavioral and Economic Sciences, Office of Multidisciplinary Activities and Division of Behavioral and Cognitive Sciences.





