---
title: "Workshop"
---

The workshop for OCCTIVE adopters will be at Union College, November 18-19.  

If you are interested in participating, complete [this form](https://forms.gle/BUNLRzQes6qQ5qq46).  **NOTE: For planning purposes, we request that you complete the participation form by September 16, 2024).**

This workshop will be a 1.5 day opportunity for non-CS faculty to work with the OCCTIVE grant team on ways to incorporate the video toolkit into their courses.  The NSF funding provides support for adopting faculty in the form of:

* Reasonable travel expenses to attend the workshop
* 2 nights of hotel accommodation during the workshop (3 nights for people whose flight options are limited) and all workshop meals
* Stipends for integrating OCCTIVE into a course, sharing relevant course material, and helping the grant team collect data to assess the video library

At our own schools, interested faculty have come from a wide range of fields: Economics, Geology, Biology/Ecology, Physics, Astronomy, Chemistry, Statistics, Sociology, Psychology, Environmental Science.  Of course, we welcome participants from the full range of academic disciplines!!  If you are interested in participating, there's more info [here](recruitmentInfo.html), or you can contact the [PI team at](mailto:occtive@gmail.com), or complete [this form](https://forms.gle/BUNLRzQes6qQ5qq46).  **NOTE: For planning purposes, we request that you complete the participation form by September 16, 2024).**

